### ISSUE TITLE
no service shown on host

### ISSUE THREAD

**Issue by nikomaxi** [zaphbbrox/letsencrypt_certs#1]
I have placed the file • / local / share / check_mk / checks / letsencrypt
and / local / share / check_mk / web / plugins / wato / check_parameters_letsencrypt.py

i have also places the file  / plugin / letsencrypt_certs at the target where my agent is installed, there are already other python checks. 
I have also run check_mk_agent register, and it shows, that the script is executed, but I don't get the services listed on my dashboard for the host. 

What can I do?

**Comment by zaphbbrox** [comment]
Tbh it's been quite a while since I had to configure it on the CheckMK host.  
With [Werk #10601](https://checkmk.com/werk/10601) the plugin API changed, but the old structure should still be supported.  
My CheckMK server is running on the latest version, so this should not be the problem.

On the destinaton server I put the plugin under `/usr/lib/check_mk_agent/plugins` and do a rescan for the host.  
Afterwards all currently installed LetsEncrypt certificates show up.

Check if the plugin script is marked as executable.  
If not you can make it so with:
~~~
chmod u+x letsencrypt_certs
~~~
